FROM node:20-slim

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальное
COPY . .

EXPOSE 5173

# Запускаем Vite с флагом --host, чтобы он принимал соединения извне контейнера
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]